env:
  MAVEN_OPTS: -Xmx1g -Xmx1g
java-version: 11
issue-reporting:
  comments: true
  labels:
   success: CI-Success
   failure: CI-Failure
end-job:
  if: ${{ always() }}
  steps:
    - name: test
      run: |-
        echo hello
        ls -al ${OB_ARTIFACTS_DIR}
   
