env:
  MAVEN_OPTS: -Xmx1g -Xmx1g
java-version: 11
issue-reporting:
  comments: true
  labels:
   success: CI-Success
   failure: CI-Failure
end-job:
  if: ${{ always() }}
  runs-on: 
    - end-job
  steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"   
    - name: test
      run: |-
        ls -al ${OB_ARTIFACTS_DIR}
        IP_ADDR=$(hostname -I)
        TGT_FOLDER=/var/www/html/issue-${OB_ISSUE_ID}
        sudo rm -rf ${TGT_FOLDER}/*
        sudo mkdir -p ${TGT_FOLDER}
        if [ -f ${OB_ARTIFACTS_DIR}/wildfly.zip ]; then
          sudo cp ${OB_ARTIFACTS_DIR}/wildfly.zip ${TGT_FOLDER}
        fi
        if [ -f ${OB_ARTIFACTS_DIR}/maven-repo.zip ]; then
          sudo cp ${OB_ARTIFACTS_DIR}/maven-repo.zip ${TGT_FOLDER}
        fi
        
        # Link to the artifacts
        echo Artifacts can be downloaded from http://${IP_ADDR}/issue-${OB_ISSUE_ID} >> $OB_STATUS_TEXT
        # Link to the workflow 
        echo https://github.com/${{github.repository}}/actions/runs/${{github.run_id}} >> $OB_STATUS_TEXT
