env:
  MAVEN_SMOKE_TEST_PARAMS: -Dmaven.test.failure.ignore=true -DfailIfNoTests=false -Dipv6 -Djboss.test.transformers.eap -Dci-cleanup=true -fae
  MAVEN_TEST_PARAMS: ${MAVEN_SMOKE_TEST_PARAMS} -DallTests
jobs:
  # Build the server skipping tests for speed since other jobs depend on this. The maven repo is cached
  build:
    env:
      MAVEN_BUILD_PARAMS: ${MAVEN_TEST_PARAMS} -DlegacyBuild -DlegacyRelease -DskipTests
    run:
      - mvn: install {MAVEN_BUILD_PARAMS}
      - shell: echo "build done!"

  #####################################
  # Parallel tests - depend on wildfly-core-build

  # Build the server again and run all the unit and smoke tests
  # it is different from the other testsuite tests in that we want to build everything up to and including
  # the smoke tests
  ts-smoke:
    needs: [wildfly-core-build]
    run:
      - mvn: package ${MAVEN_SMOKE_TEST_PARAMS}


  ts-domain:
    needs: [wildfly-core-build]
    run:
      - mvn: package {MAVEN_TEST_PARAMS} -pl domain

  ts-rbac:
    needs: [wildfly-core-build]
    run:
      - mvn: package ${MAVEN_TEST_PARAMS} -pl rbac

  # TODO - add all the other modules

  #####################################
  # Parallel tests - END
