# Workflow to kick off a cross component build
# It creates a branch with a generated action

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [opened, edited, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # The personal access token must be something which has the workflow permissions
        # (I also used repo, admin:repo_hook and user)
        token: ${{ secrets.OB_MULTI_CI_PAT }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    # Either build the tool with Maven, or download it from the releases
    # Maven:
    - uses: actions/checkout@v2
      with:
        #repository: overbaard/multi-repo-ci
        repository: kabir/multi-repo-ci
        ref: status-issue-report
        path: .ci-tools
    - name: Build with Maven
      working-directory: .ci-tools
      run: |
        mvn -B package
        echo "::set-env name=TOOL_JAR::.ci-tools/target/multi-repo-ci-tool.jar"
        cp target/multi-repo-ci-tool.jar ..
      # Download
#    - name: Download multi-repo-ci-tool.jar
#      run: |
#        wget http://github.com/overbaard/multi-repo-ci/releases/latest/download/multi-repo-ci-tool.jar
#        echo "::set-env name=TOOL_JAR::multi-repo-ci-tool.jar"

    - name: Create branch
      run: |
        git branch
        BRANCH=multi-repo-ci-branch-${{ github.event.issue.number }}
        git checkout -b "${BRANCH}"
        git config --global user.email "ci@example.com"
        git config --global user.name "CI Action"
        echo "${{ github.event.issue.body }}" > config.yml
        java -jar ${TOOL_JAR} generate-workflow --workflow-dir=.github/workflows --yaml=config.yml --issue=${{ github.event.issue.number }} --branch=$BRANCH
        git add -A
        git commit -m "Testing file for #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
        git push --force origin "${BRANCH}"
