# Workflow to kick off a cross component build
# It creates a branch with a generated action

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [opened, edited, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: |
        mvn -B package

    - name: Create branch
      run: |
        git branch
        BRANCH=branch-${{ github.event.issue.number }}
        git checkout -b "${BRANCH}"
        git config --global user.email "ci@example.com"
        git config --global user.name "CI Action"
        echo "${{ github.event.issue.body }}" > config.yml
        java -jar target/ci-tool.jar --workflow-dir=.github/workflows --yaml=config.yml --issue=${{ github.event.issue.number }} --branch=$BRANCH
        git add -A
        git commit -m "Add file"
        git push --force origin "${BRANCH}"

    # Runs a set of commands using the runners shell
    # - name: Env
    #   run: env
      
    # - name: Output GITHUB_EVENT_PATH
    #   run: |
    #     cat $GITHUB_EVENT_PATH
    #
    # - name: use github event
    #   run: |
    #     echo ${{ github.event.issue.number }}
    #     echo "${{ github.event.issue.body }}"
