# A temporary workflow to try things out quickly

name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # The personal access token must be something which has the workflow permissions
        # (I also used repo, admin:repo_hook and user)
        token: ${{ secrets.CI_PAT }}

    - name: Check branch
      run: |
        git remote show origin
        git config --global user.email "ci@example.com"
        git config --global user.name "CI Action"
        git checkout -b quick-branch
        mv .github/workflows/created.bak .github/workflows/created.yml
        git add -A
        DATE=$(date)
        git commit -m "Create throwaway.yml - ${DATE}"
        git push --force origin quick-branch
