name: WildFly Only
'on':
  push:
    branches: scratch
env:
  MAVEN_OPTS: -Xms756M -Xmx1g
jobs:
  sample:
    name: wildfly-build
    runs-on:
    - ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"


