name: WildFly Only
'on':
  push:
    branches: scratch
env:
  MAVEN_OPTS: -Xms756M -Xmx1g
jobs:
  sample:
    name: wildfly-build
    runs-on:
    - ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:  
    - run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}


