# Workflow to kick off a cross component build
# It creates a branch with a generated action

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: |
      echo home: ${HOME}
      echo workspace: ${GITHUB_WORKSPACE}
      echo pwd on next line
      pwd
